Added BitBar plugin
SeerUK/tid pull request #2
Opened 2017-04-14 22:10 UTC by cj123

[BitBar](https://github.com/matryer/bitbar) allows for simple plugins written with bash (etc).

I've put together this simple script to pull the information out of tid's status command, with resume and stop features for the current running timer.

![image](https://cloud.githubusercontent.com/assets/306873/25057423/901dbdfa-2167-11e7-94c7-8cc543e0285c.png)

2017-04-14 22:44 UTC, cj123 commented
Just noticed that this does not handle the case where there is no timer available to check the status of, when `tid status` returns "status: No timer to check the status of". (e.g. if you create and switch to a new workspace and then run the status command)

This actually leads to the statusbar showing "No", which isn't ideal 😄 .

I think making `tid status` exit with non-zero status in this case, and then detecting and handling it suitably in the plugin would be the best way of fixing this issue. Thoughts?

2017-04-18 21:49 UTC, SeerUK commented
Aah, that last part definitely needs changing when you're using `--format`, it should just output nothing in that case. I think you may have already covered the other half of that - setting error codes in those cases, so that scripts can react to no entries being found easier.

2017-04-23 19:44 UTC, n7st commented
I've written a plugin in a fork [here](https://github.com/n7st/tid/tree/development/extras/i3blocks) for i3blocks (i3wm status bar), in case that's of any interest. It does need updating to read exit codes rather than using magic strings.

2017-04-25 07:20 UTC, SeerUK commented
Aha excellent. I'd only said to Callum the other day that it'd be great to have something for Linux (especially happy there because I've been considering the move to i3 for a while).

I'd love to see a PR!

2017-04-26 09:08 UTC, seeruk requested changes

2017-04-26 09:08 UTC, SeerUK commented on pkg/tid/cli/command/entry/list.go
> +			output.SetExitCode(1)
For these, I think we've already discussed, you can instead return an error to have it be a one-liner that sets the exit code too (though the addition of SetExitCode is still very useful).

2017-04-26 09:08 UTC, SeerUK commented on pkg/tid/cli/command/entry/update.go
> +			output.SetExitCode(1)
Same for the other instances of this.

2017-04-26 09:08 UTC, SeerUK commented on glide.lock
> +  version: 1db5440ff756bcce3db592399d21b8f77e32b5f1
I'm gonna check this now and see if we can release a new minor version.

2017-04-26 09:10 UTC, SeerUK commented on glide.lock
> +  version: 1db5440ff756bcce3db592399d21b8f77e32b5f1
v0.2.1 has been released, that should make this a bit safer.

2017-04-26 13:38 UTC, seeruk approved these changes

2017-04-26 13:38 UTC, merged